version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    restart: always
    # ports:
    #     - "3306:3306"
    volumes:
     - ./.sqlData:/var/lib/mysql
    env_file:
        - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    # ports:
    #     - "6379:6379"
    volumes:
     - ./.redisData:/data
    env_file:
    - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

  spring:
    build: 
      context: server
      args:
        GITHUB_BE_REPO_PATH: ${GITHUB_BE_REPO_PATH}
        GIT_TOKEN: ${GIT_TOKEN}
    container_name: spring
    hostname: spring
    restart: always
    # ports:
    #     - "8080:8080"
    env_file:
        - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    depends_on:
      - mysql
      - redis

  client:
    build: 
      context: client
      args:
        GITHUB_FE_REPO_PATH: ${GITHUB_FE_REPO_PATH}
        GIT_TOKEN: ${GIT_TOKEN}
        APP_DOMAIN: ${APP_DOMAIN}
        VITE_API_ENDPOINT: ${VITE_API_ENDPOINT}
        VITE_NODE_ENV: ${VITE_NODE_ENV}
    container_name: client
    hostname: client
    restart: always
    # ports:
    #     - "3000:3000"
    env_file:
        - .env
    environment:
      APP_DOMAIN: ${APP_DOMAIN}

  proxy:
    build: 
      context: proxy
      args:
        APP_DOMAIN: ${APP_DOMAIN}
        API_HOST: ${API_HOST}
        CLIENT_HOST: ${CLIENT_HOST}
    container_name: proxy
    hostname: proxy
    restart: always
    ports:
        - "443:443"
        - "80:80"
    env_file:
        - .env
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      API_HOST: ${API_HOST}
      CLIENT_HOST: ${CLIENT_HOST}
    volumes:
      - ./.certbot/www:/var/www/certbot/:ro
      - ./.certbot/conf/:/etc/letsencrypt/:ro
    depends_on:
      - mysql
      - redis
      - client
      - spring

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./.certbot/www/:/var/www/certbot/:rw
      - ./.certbot/conf/:/etc/letsencrypt/:rw

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400