version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./.sqlData:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./.redisData:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  spring:
    image: my-spring-image
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      RECAPTCHA_SITE: ${RECAPTCHA_SITE}
      RECAPTCHA_SECRET: ${RECAPTCHA_SECRET}
      APP_DOMAIN: ${APP_DOMAIN}
      SPRING_ENV: ${SPRING_ENV}
      DASHBOARD_LIMIT: ${DASHBOARD_LIMIT}
      CHART_LIMIT: ${CHART_LIMIT}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  client:
    image: my-client-image
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  proxy:
    image: my-proxy-image
    ports:
      - "443:443"
      - "80:80"
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      API_HOST: ${API_HOST}
      CLIENT_HOST: ${CLIENT_HOST}
    volumes:
      - ./.certbot/www:/var/www/certbot/:ro
      - ./.certbot/conf/:/etc/letsencrypt/:ro
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./.certbot/www/:/var/www/certbot/:rw
      - ./.certbot/conf/:/etc/letsencrypt/:rw

networks:
  default:
    driver: overlay
